[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "muzzle"
authors = [{name = "Stefan Oderbolz", email = "odi@metaodi.ch"}]
readme = "README.md"
requires-python = ">=3.9"
classifiers = ["License :: OSI Approved :: MIT License"]
description = "A tiny xmlparser"
dynamic = ["version"]
dependencies = [
    "defusedxml",
    "xmltodict",
]

[project.optional-dependencies]
test = [
    "black",
    "flake8",
    "mock",
    "mypy",
    "pytest",
    "pytest-cov",
]

[project.urls]
Home = "https://github.com/metaodi/muzzle"

[tool.mypy]
ignore_missing_imports = true

[tool.hatch.version]
path = "muzzle/__init__.py"
